### ISSUE TITLE
Using software serial is unreliable

### ISSUE THREAD

**Issue by philippejadin** [elkayem/midi2cv#13]
Just for those trying to use software serial to connect a midi input, it is unreliable and not advised : 
https://arduino.stackexchange.com/questions/38567/softwareserial-too-slow-for-midi

The problem I was trying to fix was that one cannot program the arduino if the optocoupler is connected to the RX pin. A somewhat nice fix would be to put a jumper that must be removed when you want to reprogram the arduino. (this is with an arduino clone with the ch340 driver, so maybe this would work fine with a genuine nano)

Or did I miss something?

**Comment by elkayem** [comment]
Regarding SoftwareSerial... this code does not use it so I cannot see this is an issue for this code. 

Addressing your second comment, agreed that you cannot program the nano while it is plugged into the board due to the 500 ohm optocoupler resistor pulling RX up to 5V. As a general practice on any board, I would recommend unplugging the nano before programming it. This is the easiest solution. A custom solution may be needed if your board is inaccessible.
